### ISSUE TITLE
More graceful error handling/display in bento archive

### ISSUE THREAD

**Issue by arashd** [returntocorp/bento#109]
**Describe the bug**
When one of the linters (in this case EsLint) errors out while running the archive command, we should tell the user what happened. 

**Expected result**
Bento tells me that eslint failed but results for the other linters were archived.

**Actual result**
```bach
$ bento archive
  r2c.bandit: |███████████████| 00:01, 🍱
  r2c.eslint: |██████▌        | 00:03, 🍤
  r2c.flake8: |███████████████| 00:03, 🍱

⚠ Could not execute "./node_modules/eslint/bin/eslint.js --no-eslintrc -c .eslintrc.yml -f json --ignore-pattern **/node_modules --ext js,jsx,ts,tsx .":
TypeError: Cannot read property 'match' of undefined
Occurred while linting /Users/arashdelijani/workspace/bento-tests/minimal-flask-react/src/index.jsx:1
    at countTrailingLinebreaks (/Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:792:47)
    at /Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:859:65
    at Array.forEach (<anonymous>)
    at addElementListIndent (/Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:834:22)
    at Object.addFunctionCallIndent [as listener] (/Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:927:13)
    at /Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:1585:55
    at Array.forEach (<anonymous>)
    at Program:exit (/Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/rules/indent.js:1585:26)
    at /Users/arashdelijani/workspace/bento-tests/minimal-flask-react/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>)
```

**Additional context**
running `bento archive` with version `bento/0.1.1b4` on `https://github.com/jwkvam/minimal-flask-react@f070c9d5`

**Comment by dlukeomalley** [comment]
Closing for now as we've deprioritized `eslint`. @arashd Is this issue still relevant for other tools?
