### ISSUE TITLE
bento init fails when .npm not installed 

### ISSUE THREAD

**Issue by embailie** [returntocorp/bento#110]
I am running bento version 0.1.1b4
**Describe the bug**
When running `bento init` for a project without npm installed in dev environment, the following failure occurs:
```Installing {'eslint': Version('6.1.0'), 'eslint-config-airbnb': Version('18.0.1'), 'eslint-plugin-import': Version('2.18.2'), 'eslint-plugin-jsx-a11y': Version('6.2.3'), 'eslint-plugin-react': Version('7.14.3'), 'eslint-plugin-react-hooks': Version('1.7.0')}...
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bento/__main__.py", line 14, in main
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/bento/cli.py", line 539, in init
    t.setup(config)
  File "/usr/local/lib/python3.7/site-packages/bento/extra/eslint.py", line 133, in setup
    self._ensure_packages(needed_packages)
  File "/usr/local/lib/python3.7/site-packages/bento/extra/js_tool.py", line 60, in _ensure_packages
    self._npm_install(to_install)
  File "/usr/local/lib/python3.7/site-packages/bento/extra/js_tool.py", line 41, in _npm_install
    self.exec(cmd + args, check=True)
  File "/usr/local/lib/python3.7/site-packages/bento/tool.py", line 157, in exec
    return subprocess.run(command, **new_args)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 1522, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
NotADirectoryError: [Errno 20] Not a directory: 'npm'
✘ There was an exception [Errno 20] Not a directory: 'npm'```

**Expected result**
A more graceful message declaring need for npm

**Actual result**
See above

**Comment by nbrahms** [comment]
Relates to #114

**Comment by dlukeomalley** [comment]
@embailie @nbrahms Closing this as stale for now. Long term we'll need to address issues like this and I appreciate you filing @embailie! For now, we expect developers working on node js projects will have npm installed already. Let's revisit if that assumption proves incorrect.
