### ISSUE TITLE
`bento setup` failure on ubuntu 18.04

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#17]
user reports: (might be a pip python2 vs 3 thing on my computer). Ubuntu 18.04.

>$ bento setup
Creating default configuration at ./.bento.yml
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/bento/__main__.py", line 10, in main
    cli()
  File "/home/erik/.local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/erik/.local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/erik/.local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/erik/.local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/erik/.local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/bento/cli.py", line 170, in setup
    t.setup(config)
  File "/usr/local/lib/python3.6/dist-packages/bento/extra/eslint.py", line 95, in setup
    eslint_version = self.__installed_version("eslint")
  File "/usr/local/lib/python3.6/dist-packages/bento/extra/eslint.py", line 77, in __installed_version
    ["npm", "list", "--depth=0", pkg], capture_output=True
  File "/usr/local/lib/python3.6/dist-packages/bento/tool.py", line 80, in exec
    return subprocess.run(command, **new_args)
  File "/usr/lib/python3.6/subprocess.py", line 423, in run
    with Popen(*popenargs, **kwargs) as process:
TypeError: __init__() got an unexpected keyword argument 'capture_output'
There was an exception __init__() got an unexpected keyword argument 'capture_output'

**Comment by deifactor** [comment]
capture_output was added in 3.7, hence the error.

**Comment by dlukeomalley** [comment]
I believe this was corrected on develop and our upcoming release. Tagging as `release-blocking` to ensure that we test this and ship it. CC @nbrahms

**Comment by nbrahms** [comment]
This will still fail due to missing `importlib.resources`

**Comment by dlukeomalley** [comment]
Another user hit this error. Environment details:

```bash
$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

$ python3 --version
Python 3.6.8
```

Error message:

```bash
$ bento --version
Traceback (most recent call last):
  File "/home/pad/.local/bin/bento", line 7, in <module>
    from bento.__main__ import main
  File "/home/pad/.local/lib/python3.6/site-packages/bento/__main__.py", line 8, in <module>
    from bento.cli import cli
  File "/home/pad/.local/lib/python3.6/site-packages/bento/cli.py", line 22, in <module>
    import bento.extra
  File "/home/pad/.local/lib/python3.6/site-packages/bento/extra/__init__.py", line 3, in <module>
    from bento.extra.bandit import BanditTool
  File "/home/pad/.local/lib/python3.6/site-packages/bento/extra/bandit.py", line 6, in <module>
    from bento.extra.python_tool import PythonTool
  File "/home/pad/.local/lib/python3.6/site-packages/bento/extra/python_tool.py", line 11, in <module>
    import bento.tool
  File "/home/pad/.local/lib/python3.6/site-packages/bento/tool.py", line 6, in <module>
    import bento.util
  File "/home/pad/.local/lib/python3.6/site-packages/bento/util.py", line 15, in <module>
    from importlib.resources import open_binary, read_text
ModuleNotFoundError: No module named 'importlib.resources'
```

**Comment by nbrahms** [comment]
Dear @dlukeomalley ... I've confirmed that bento runs properly on Python 3.6 with version 0.1.0r3. I have not confirmed Ubuntu specifically. @pabloest would love if you can confirm using 0.1.0r3!
