### ISSUE TITLE
No such file or directory 'node' causes Bento check step of GitHub Action to fail

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#276]
I installed the GitHub Action following the [instructions in the marketplace](https://github.com/marketplace/actions/bento-action).

I am using Bento version `bento/0.9.1` on my computer.

After making a PR on the bento-web repo, I see the action begins and I went to view the “Bento checks” output in the GitHub Action panel. There I see an error. It’s a bit tricky to copy/paste directly from the Action page so here is the `4_bento checks.txt` log file I got from downloading the logs:

```
2020-02-14T23:47:45.6277223Z ##[group]Run returntocorp/bento-action@v1
2020-02-14T23:47:45.6277519Z with:
2020-02-14T23:47:45.6277608Z   acceptTermsWithEmail: pablo@r2c.dev
2020-02-14T23:47:45.6277732Z ##[endgroup]
2020-02-14T23:47:45.6310718Z ##[command]/usr/bin/docker run --name dfbe850058180954b24933d06a532146880_6e4fe1 --label 488dfb --workdir /github/workspace --rm -e INPUT_ACCEPTTERMSWITHEMAIL -e HOME -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e RUNNER_OS -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/bento-web/bento-web":"/github/workspace" 488dfb:e850058180954b24933d06a532146880
2020-02-14T23:47:47.3584226Z action's environment: bento/0.8.2, Python 3.8.1, Docker version 19.03.6, build 369ce74a3c
2020-02-14T23:47:47.3584756Z 
2020-02-14T23:47:47.3585782Z == [1/4] we're going to go back to the commit you based your pull request on…
2020-02-14T23:47:47.3585916Z 
2020-02-14T23:47:48.0016891Z Unstaged changes after reset:
2020-02-14T23:47:48.0017837Z D	.github/workflows/bento.yml
2020-02-14T23:47:48.0018951Z M	README.md
2020-02-14T23:47:48.0020226Z M	gatsby-config.js
2020-02-14T23:47:48.0020843Z M	package.json
2020-02-14T23:47:48.0021477Z M	public/blog/2020/bento-0.8-released-with-updated-workflows-and-new-specialty-checks/twitter-card.jpg
2020-02-14T23:47:48.0022479Z D	public/blog/2020/bento-check-catch-catastrophic-backtracking-redos-bugs/twitter-card.jpg
2020-02-14T23:47:48.0023431Z D	public/cb6bf46e29d584427f52c8c3c27033b6/redos-backtracking-example.gif
2020-02-14T23:47:48.0024374Z M	public/checks/boto3/hardcoded-access-token/twitter-card.jpg
2020-02-14T23:47:48.0025689Z D	public/checks/jinja/anchor-href-template-variable/twitter-card.jpg
2020-02-14T23:47:48.0026542Z D	public/checks/jinja/anchor-missing-noopener/twitter-card.jpg
2020-02-14T23:47:48.0027185Z D	public/checks/jinja/anchor-missing-noreferrer/twitter-card.jpg
2020-02-14T23:47:48.0028049Z D	public/checks/jinja/form-missing-csrf-protection/twitter-card.jpg
2020-02-14T23:47:48.0028924Z D	public/checks/jinja/missing-doctype/twitter-card.jpg
2020-02-14T23:47:48.0029645Z D	public/checks/jinja/missing-meta-charset/twitter-card.jpg
2020-02-14T23:47:48.0030549Z D	public/checks/jinja/missing-meta-content-type/twitter-card.jpg
2020-02-14T23:47:48.0031136Z D	public/checks/jinja/unquoted-attribute-template-variable/twitter-card.jpg
2020-02-14T23:47:48.0031487Z M	public/index.html
2020-02-14T23:47:48.0032106Z M	public/page-data/404.html/page-data.json
2020-02-14T23:47:48.0032655Z M	public/page-data/404/page-data.json
2020-02-14T23:47:48.0033655Z M	public/page-data/blog/2019/flask-check-send-file/page-data.json
2020-02-14T23:47:48.0034306Z M	public/page-data/blog/2019/our-quest-to-make-world-class-security-and-bugfinding-available-to-all-developers/page-data.json
2020-02-14T23:47:48.0034923Z M	public/page-data/blog/2019/three-things-your-linter-shouldnt-tell-you/page-data.json
2020-02-14T23:47:48.0037431Z M	public/page-data/blog/2020/bento-0.8-released-with-updated-workflows-and-new-specialty-checks/page-data.json
2020-02-14T23:47:48.0037836Z D	public/page-data/blog/2020/bento-check-catch-catastrophic-backtracking-redos-bugs/page-data.json
2020-02-14T23:47:48.0038196Z M	public/page-data/blog/2020/bento-check-keeping-cookies-safe-in-flask/page-data.json
2020-02-14T23:47:48.0038539Z M	public/page-data/blog/2020/bento-check-securing-your-flask-routes/page-data.json
2020-02-14T23:47:48.0038884Z M	public/page-data/blog/2020/bento-check-unescaped-template-extensions-in-flask/page-data.json
2020-02-14T23:47:48.0039188Z M	public/page-data/blog/2020/bento-check-use-jsonify-instead-of-json-dumps-in-flask/page-data.json
2020-02-14T23:47:48.0040206Z M	public/page-data/blog/2020/personal-and-team-use-in-bento-08/page-data.json
2020-02-14T23:47:48.0040527Z M	public/page-data/blog/page-data.json
2020-02-14T23:47:48.0040841Z M	public/page-data/checks/boto3/hardcoded-access-token/page-data.json
2020-02-14T23:47:48.0041241Z M	public/page-data/checks/click/launch-uses-literal/page-data.json
2020-02-14T23:47:48.0041627Z M	public/page-data/checks/click/option-function-argument-check/page-data.json
2020-02-14T23:47:48.0041958Z M	public/page-data/checks/flask/avoid-hardcoded-config/page-data.json
2020-02-14T23:47:48.0042263Z M	public/page-data/checks/flask/missing-jwt-token/page-data.json
2020-02-14T23:47:48.0042569Z M	public/page-data/checks/flask/secure-set-cookie/page-data.json
2020-02-14T23:47:48.0042830Z M	public/page-data/checks/flask/send-file-open/page-data.json
2020-02-14T23:47:48.0043146Z M	public/page-data/checks/flask/unescaped-file-extension/page-data.json
2020-02-14T23:47:48.0043479Z M	public/page-data/checks/flask/use-blueprint-for-modularity/page-data.json
2020-02-14T23:47:48.0043803Z M	public/page-data/checks/flask/use-jsonify/page-data.json
2020-02-14T23:47:48.0044078Z D	public/page-data/checks/jinja/anchor-href-template-variable/page-data.json
2020-02-14T23:47:48.0044401Z D	public/page-data/checks/jinja/anchor-missing-noopener/page-data.json
2020-02-14T23:47:48.0044762Z D	public/page-data/checks/jinja/anchor-missing-noreferrer/page-data.json
2020-02-14T23:47:48.0045081Z D	public/page-data/checks/jinja/form-missing-csrf-protection/page-data.json
2020-02-14T23:47:48.0045344Z D	public/page-data/checks/jinja/missing-doctype/page-data.json
2020-02-14T23:47:48.0045657Z D	public/page-data/checks/jinja/missing-meta-charset/page-data.json
2020-02-14T23:47:48.0045972Z D	public/page-data/checks/jinja/missing-meta-content-type/page-data.json
2020-02-14T23:47:48.0046313Z D	public/page-data/checks/jinja/unquoted-attribute-template-variable/page-data.json
2020-02-14T23:47:48.0046561Z M	public/page-data/checks/page-data.json
2020-02-14T23:47:48.0046905Z M	public/page-data/checks/requests/no-auth-over-http/page-data.json
2020-02-14T23:47:48.0047228Z M	public/page-data/checks/requests/use-scheme/page-data.json
2020-02-14T23:47:48.0047533Z M	public/page-data/checks/requests/use-timeout/page-data.json
2020-02-14T23:47:48.0047787Z M	public/page-data/dev-404-page/page-data.json
2020-02-14T23:47:48.0048098Z M	public/page-data/index/page-data.json
2020-02-14T23:47:48.0048236Z M	public/static/d/1317303708.json
2020-02-14T23:47:48.0048360Z M	public/static/d/2824319322.json
2020-02-14T23:47:48.0048435Z M	public/static/d/3548875354.json
2020-02-14T23:47:48.0048558Z M	public/static/d/679924463.json
2020-02-14T23:47:48.0048921Z D	public/static/db8eaf1e27ddedd4bd78f073e86a395b/135ae/redos-initial-findings-by-commit-hash.png
2020-02-14T23:47:48.0049274Z D	public/static/db8eaf1e27ddedd4bd78f073e86a395b/34e8a/redos-initial-findings-by-commit-hash.png
2020-02-14T23:47:48.0049762Z D	public/static/db8eaf1e27ddedd4bd78f073e86a395b/6ff5e/redos-initial-findings-by-commit-hash.png
2020-02-14T23:47:48.0141107Z D	public/static/db8eaf1e27ddedd4bd78f073e86a395b/d02d5/redos-initial-findings-by-commit-hash.png
2020-02-14T23:47:48.0141556Z M	src/components/checks-nav.js
2020-02-14T23:47:48.0141928Z M	src/components/helmet.js
2020-02-14T23:47:48.0142092Z M	src/components/navbar.js
2020-02-14T23:47:48.0142177Z M	src/components/style.scss
2020-02-14T23:47:48.0142778Z M	src/pages/blog/2020/bento-0.8-released-with-updated-workflows-and-new-specialty-checks.md
2020-02-14T23:47:48.0143124Z M	src/pages/blog/2020/bento-check-securing-your-flask-routes.md
2020-02-14T23:47:48.0143441Z D	src/pages/blog/images/2020/redos-backtracking-example.gif
2020-02-14T23:47:48.0143714Z D	src/pages/blog/images/2020/redos-initial-findings-by-commit-hash.png
2020-02-14T23:47:48.0143867Z M	src/pages/checks.js
2020-02-14T23:47:48.0144163Z M	src/pages/checks/boto3/hardcoded-access-token.md
2020-02-14T23:47:48.0144505Z D	src/pages/checks/jinja/anchor-href-template-variable.md
2020-02-14T23:47:48.0144765Z D	src/pages/checks/jinja/anchor-missing-noopener.md
2020-02-14T23:47:48.0145273Z D	src/pages/checks/jinja/anchor-missing-noreferrer.md
2020-02-14T23:47:48.0145606Z D	src/pages/checks/jinja/form-missing-csrf-protection.md
2020-02-14T23:47:48.0145906Z D	src/pages/checks/jinja/missing-doctype.md
2020-02-14T23:47:48.0146261Z D	src/pages/checks/jinja/missing-meta-charset.md
2020-02-14T23:47:48.0151238Z D	src/pages/checks/jinja/missing-meta-content-type.md
2020-02-14T23:47:48.0151618Z D	src/pages/checks/jinja/unquoted-attribute-template-variable.md
2020-02-14T23:47:48.0151766Z M	src/pages/index.js
2020-02-14T23:47:48.0151843Z M	yarn.lock
2020-02-14T23:47:48.0151971Z 
2020-02-14T23:47:48.0152360Z == [2/4] …checking what issues the codebase had before your pull request…
2020-02-14T23:47:48.0152430Z 
2020-02-14T23:47:49.8098662Z 
2020-02-14T23:47:49.8099735Z ╭─────────────────────────────────────────────╮
2020-02-14T23:47:49.8100101Z │  🎉 A new version of Bento is available 🎉  │
2020-02-14T23:47:49.8100520Z │  Try it out by running:                     │
2020-02-14T23:47:49.8100936Z │                                             │
2020-02-14T23:47:49.8101226Z │       pip3 install --upgrade bento-cli      │
2020-02-14T23:47:49.8101506Z │                                             │
2020-02-14T23:47:49.8101812Z ╰─────────────────────────────────────────────╯
2020-02-14T23:47:49.8101907Z 
2020-02-14T23:47:49.8107083Z Running Bento archive on all tracked files...
2020-02-14T23:47:49.8107156Z 
2020-02-14T23:47:50.1141193Z ✘ There was an exception [Errno 2] No such file or directory: 'node'
2020-02-14T23:47:50.7463478Z Traceback (most recent call last):
2020-02-14T23:47:50.7463691Z   File "/usr/local/bin/bento", line 8, in <module>
2020-02-14T23:47:50.7463777Z     sys.exit(main())
2020-02-14T23:47:50.7464609Z   File "/usr/local/lib/python3.8/site-packages/bento/__main__.py", line 11, in main
2020-02-14T23:47:50.7464774Z     cli(auto_envvar_prefix="BENTO")
2020-02-14T23:47:50.7465107Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 764, in __call__
2020-02-14T23:47:50.7465268Z     return self.main(*args, **kwargs)
2020-02-14T23:47:50.7465610Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 717, in main
2020-02-14T23:47:50.7465928Z     rv = self.invoke(ctx)
2020-02-14T23:47:50.7466515Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
2020-02-14T23:47:50.7466619Z     return _process_result(sub_ctx.command.invoke(sub_ctx))
2020-02-14T23:47:50.7467552Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 956, in invoke
2020-02-14T23:47:50.7467712Z     return ctx.invoke(self.callback, **ctx.params)
2020-02-14T23:47:50.7468087Z   File "/usr/local/lib/python3.8/site-packages/click/core.py", line 555, in invoke
2020-02-14T23:47:50.7468189Z     return callback(*args, **kwargs)
2020-02-14T23:47:50.7468543Z   File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 27, in new_func
2020-02-14T23:47:50.7468704Z     return f(get_current_context().obj, *args, **kwargs)
2020-02-14T23:47:50.7469090Z   File "/usr/local/lib/python3.8/site-packages/bento/decorators.py", line 110, in new_func
2020-02-14T23:47:50.7469194Z     raise exception
2020-02-14T23:47:50.7469854Z   File "/usr/local/lib/python3.8/site-packages/bento/decorators.py", line 59, in new_func
2020-02-14T23:47:50.7470169Z     res = f(*args, **kwargs)
2020-02-14T23:47:50.7470504Z   File "/usr/local/lib/python3.8/site-packages/bento/commands/archive.py", line 97, in archive
2020-02-14T23:47:50.7470594Z     raise vv
2020-02-14T23:47:50.7470935Z   File "/usr/local/lib/python3.8/site-packages/bento/tool_runner.py", line 248, in _setup_and_run_single_tool
2020-02-14T23:47:50.7471107Z     self._setup_tool(
2020-02-14T23:47:50.7471443Z   File "/usr/local/lib/python3.8/site-packages/bento/tool_runner.py", line 200, in _setup_tool
2020-02-14T23:47:50.7471597Z     tool.setup()
2020-02-14T23:47:50.7471864Z   File "/usr/local/lib/python3.8/site-packages/bento/extra/eslint.py", line 240, in setup
2020-02-14T23:47:50.7472195Z     self._ensure_node_version()
2020-02-14T23:47:50.7472559Z   File "/usr/local/lib/python3.8/site-packages/bento/extra/js_tool.py", line 107, in _ensure_node_version
2020-02-14T23:47:50.7472707Z     version = self.execute(
2020-02-14T23:47:50.7472971Z   File "/usr/local/lib/python3.8/site-packages/bento/tool.py", line 212, in execute
2020-02-14T23:47:50.7473223Z     res = subprocess.run(command, **new_args)
2020-02-14T23:47:50.7473356Z   File "/usr/local/lib/python3.8/subprocess.py", line 489, in run
2020-02-14T23:47:50.7473694Z     with Popen(*popenargs, **kwargs) as process:
2020-02-14T23:47:50.7473781Z   File "/usr/local/lib/python3.8/subprocess.py", line 854, in __init__
2020-02-14T23:47:50.7473936Z     self._execute_child(args, executable, preexec_fn, close_fds,
2020-02-14T23:47:50.7474074Z   File "/usr/local/lib/python3.8/subprocess.py", line 1702, in _execute_child
2020-02-14T23:47:50.7474214Z     raise child_exception_type(errno_num, err_msg, err_filename)
2020-02-14T23:47:50.7474510Z FileNotFoundError: [Errno 2] No such file or directory: 'node'
2020-02-14T23:47:51.0586849Z ##[error]Docker run failed with exit code 1

```

Screenshot:
<img width="1104" alt="Screen Shot 2020-02-14 at 3 56 25 PM" src="https://user-images.githubusercontent.com/302941/74577140-94235200-4f42-11ea-9fcf-b927a2146319.png">

**Comment by underyx** [comment]
Got it, just need to include node.js in the Docker image (I had made the naive assumption that `eslint` runs via docker like for instance `hadolint`). Will fix by tomorrow PST morning!

**Comment by underyx** [comment]
@pabloest could you test again and/or give me access to the failing repo?

**Comment by pabloest** [comment]
@underyx Sure. I’m not quite sure how to test the Action without making a new PR so I’ll give you access to the repo. It’s the bento-web repo, I guess you’ll get a notification about it when I add you.

**Comment by underyx** [comment]
Thank you! For reference, where you see the failed logs, there should be a re-run button, which will use the newly released code when pressed.

I'll handle it though from here.
