### ISSUE TITLE
exception while running $ bento archive

### ISSUE THREAD

**Issue by ievans** [returntocorp/bento#296]
Surprising exception occurred while running bento archive
On bento bento/0.9.1

```
ine@imbp4 ~/D/r/s/scripts (ie/refactor-sgrep-py) [1]> git diff
diff --git a/scripts/sgrep-lint/evaluation.py b/scripts/sgrep-lint/evaluation.py
index cbc8b46..da54182 100644
--- a/scripts/sgrep-lint/evaluation.py
+++ b/scripts/sgrep-lint/evaluation.py
...
```

```
ine@imbp4 ~/D/r/s/scripts (ie/refactor-sgrep-py) [1]> bento archive
Running Bento archive on staged files...

✘ There was an exception [Errno 2] No such file or directory: 'scripts/sgrep-
lint/__init__.py'
Traceback (most recent call last):
  File "/usr/local/bin/bento", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/site-packages/bento/__main__.py", line 11, in main
    cli(auto_envvar_prefix="BENTO")
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/ine/Library/Python/3.7/lib/python/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/bento/decorators.py", line 110, in new_func
    raise exception
  File "/usr/local/lib/python3.7/site-packages/bento/decorators.py", line 59, in new_func
    res = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/bento/commands/archive.py", line 88, in archive
    baseline, target_file_manager, not all_, tools
  File "/usr/local/lib/python3.7/site-packages/bento/orchestrator.py", line 31, in orchestrate
    head_baseline, elapsed = _calculate_head_comparison(target_file_manager, tools)
  File "/usr/local/lib/python3.7/site-packages/bento/orchestrator.py", line 72, in _calculate_head_comparison
    with target_file_manager.run_context(True, RunStep.BASELINE) as target_paths:
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/bento/target_file_manager.py", line 298, in run_context
    with stash_context:
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/site-packages/bento/target_file_manager.py", line 241, in _head_context
    Path(a).unlink()
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/pathlib.py", line 1294, in unlink
    self._accessor.unlink(self)
FileNotFoundError: [Errno 2] No such file or directory: 'scripts/sgrep-lint/__init__.py'
```

**Comment by nbrahms** [comment]
@ievans Can you add reproduction steps (e.g. what is your diff, bento config, and repo URL)?
