### ISSUE TITLE
eslint won't terminate

### ISSUE THREAD

**Issue by dlukeomalley** [returntocorp/bento#81]
**Describe the bug**
> I was able to set up bento-cli but ran into an issue with bento check. It seems like the check will not terminate on eslint.

**Expected result**
> Expected eslint to terminate.

**Actual result**
```bash
$ bento check
Running Bento checks...
  r2c.bandit: |███████████████| 00:03, 🍱
  r2c.eslint: |███▌           | 13:15, 🍤
  r2c.flake8: |███████████████| 00:05, 🍱

I tried re-running a few times, without success.
```

**Comment by kmwhelan93** [comment]
Some more information:

**What version of bento are you running (bento --version)?**
`bento/0.1.0`

**What operating system are you using?**
MacOS Mojave 10.14.5

**Is there anything unique about the JS/TS in your project (e.g. many lines of code, symlinks, etc.)?**
Nothing obvious comes to mind. We do not have any symlinks.

**Is there any additional info you think would help us reproduce this issue? I'm guessing your project is private, otherwise a link to the repo would be tremendous.**
Project is private :/. I could give someone temporary access for debugging.


The cli eventually failed with the output
```
$ bento check
Running Bento checks...
  r2c.bandit: |███████████████| 00:03, 🍱Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bento/tool.py", line 160, in results
    violations = self.parser().parse(raw)
  File "/usr/local/lib/python3.7/site-packages/bento/extra/eslint.py", line 63, in parse
    for r in json.loads(input):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 2 column 1 (char 1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bento/cli.py", line 184, in __tool_filter
    tool.tool_id, __tool_findings(tool, config, paths), baseline
  File "/usr/local/lib/python3.7/site-packages/bento/cli.py", line 140, in __tool_findings
    return tool.results(tool_config, paths)
  File "/usr/local/lib/python3.7/site-packages/bento/tool.py", line 162, in results
    raise Exception(f"Could not parse output of '{self.tool_id}':\n{raw}")
Exception: Could not parse output of 'r2c.eslint':

<--- Last few GCs --->

[26224:0x102801000]  1617251 ms: Mark-sweep 1285.1 (1463.8) -> 1284.8 (1464.3) MB, 4520.5 / 0.0 ms  allocation failure GC in old space requested
[26224:0x102801000]  1621265 ms: Mark-sweep 1284.8 (1464.3) -> 1284.8 (1429.3) MB, 4012.0 / 0.1 ms  last resort GC in old space requested
[26224:0x102801000]  1625193 ms: Mark-sweep 1284.8 (1429.3) -> 1284.8 (1424.3) MB, 3927.9 / 0.1 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x312c083255e9 <JSObject>
    1: filter(this=0x312ce9c1bd61 <JSArray[885495]>)
    2: Program:exit(aka Program:exit) [/Users/kevinwhelan/Git/landria-demo/client/node_modules/eslint/lib/rules/indent.js:1584] [bytecode=0x312c419f5729 offset=79](this=0x312c99f822d1 <undefined>)
    3: arguments adaptor frame: 1->0
    4: /* anonymous */(aka /* anonymous */) [/Users/kevinwhelan/Git/landria-demo/client/node_modules/eslint/lib...

  r2c.eslint: |█████████▌     | 27:05, 🍤


✘ Error while running r2c.eslint: Could not parse output of 'r2c.eslint':

<--- Last few GCs --->

[26224:0x102801000]  1617251 ms: Mark-sweep 1285.1 (1463.8) -> 1284.8 (1464.3) MB, 4520.5 / 0.0 ms  allocation failure GC in old space requested
[26224:0x102801000]  1621265 ms: Mark-sweep 1284.8 (1464.3) -> 1284.8 (1429.3) MB, 4012.0 / 0.1 ms  last resort GC in old space requested
[26224:0x102801000]  1625193 ms: Mark-sweep 1284.8 (1429.3) -> 1284.8 (1424.3) MB, 3927.9 / 0.1 ms  last resort GC in old space requested


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x312c083255e9 <JSObject>
    1: filter(this=0x312ce9c1bd61 <JSArray[885495]>)
    2: Program:exit(aka Program:exit) [/Users/kevinwhelan/Git/landria-demo/client/node_modules/eslint/lib/rules/indent.js:1584] [bytecode=0x312c419f5729 offset=79](this=0x312c99f822d1 <undefined>)
    3: arguments adaptor frame: 1->0
    4: /* anonymous */(aka /* anonymous */) [/Users/kevinwhelan/Git/landria-demo/client/node_modules/eslint/lib...
```

**Comment by nbrahms** [comment]
Hi @kmwhelan93 ,

Would you be able to run the following, and send us the output? (You can send to @dlukeomalley privately):

`node_modules/eslint/bin/eslint.js --no-eslintrc -c .eslintrc.yml --debug .`

From the root of your codebase?

**Comment by kmwhelan93** [comment]
Thanks @nbrahms. Just ran the command and sent it over to @dlukeomalley. It looks like its scanning all of our build output, which, because that includes electron, is quite large.

**Comment by nbrahms** [comment]
Hi @kmwhelan93 . Thanks for sending us the output. It's clear that `bento` should, at the very least, ignore the contents of bundled `node_modules` directories.

I don't think we have a good story yet about detecting things like `dist` directories.

I know it's not the best solution, but to unblock yourself, you could add an `.eslintignore` file to your project root to ignore `**/node_modules` and `**/dist` directories.

I'll work on integrating automated detection / path ignores into our next release.

All the best!

**Comment by kmwhelan93** [comment]
Thanks! I'll give that a try. 

Unrelated question -- does `bento init` do an `npm install` somewhere? We use yarn, so I ended up with a `package-lock.json` (we use `yarn.lock`) and in turn I believe I ended up with different dependencies.

**Comment by dmontagu** [comment]
Sounds like another vote in favor of addressing https://github.com/returntocorp/bento/issues/18

**Comment by nbrahms** [comment]
Hi @kmwhelan93 ... I opened #98 for the yarn issue. Thanks for pointing it out.

**Comment by dlukeomalley** [comment]
Hey all, thank you for the conversation and work arounds posted here. I'm going to close out this issue in favor of #18 and #98. Thank you!
