### ISSUE TITLE
Exception: Could not parse output of 'r2c.eslint'

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#82]
A user reported this issue via email.

**Describe the bug**
Bento traceback error

**Actual result**
```bash
Mac-Pro$ bento check
Running Bento checks...
  r2c.bandit: |               | 00:00, 🍜Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bento/tool.py", line 160, in results
    violations = self.parser().parse(raw)
  File "/usr/local/lib/python3.7/site-packages/bento/extra/eslint.py", line 63, in parse
    for r in json.loads(input):
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bento/cli.py", line 184, in __tool_filter
    tool.tool_id, __tool_findings(tool, config, paths), baseline
  File "/usr/local/lib/python3.7/site-packages/bento/cli.py", line 140, in __tool_findings
    return tool.results(tool_config, paths)q  File "/usr/local/lib/python3.7/site-packages/bento/tool.py", line 162, in results
    raise Exception(f"Could not parse output of '{self.tool_id}':\n{raw}")
Exception: Could not parse output of 'r2c.eslint':

  r2c.bandit: |███████████████| 00:02, 🍱
  r2c.eslint: |███████        | 00:08, 🍤
  r2c.flake8: |███████████████| 00:08, 🍱
                                                 

✘ Error while running r2c.eslint: Could not parse output of 'r2c.eslint':
                                                 



vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.1/ext/nokogiri/tmp/x86_64-apple-darwin13.2.0/ports/libxml2/2.8.0/libxml2-2.8.0/check-relaxng-test-suite.py
  0:0  error   syntax error while parsing AST from file                     r2c.bandit     error
 50:17 error   .has_key() is deprecated, use 'in'                           r2c.flake8     W601 https://lintlyci.github.io/Flake8Rules/rules/W601.html
 79:44 error   TabError: inconsistent use of tabs and spaces in indentation r2c.flake8     E999
 84:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
 97:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
125:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
137:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
166:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
192:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
214:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
239:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html

vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.1/ext/nokogiri/tmp/x86_64-apple-darwin13.2.0/ports/libxml2/2.8.0/libxml2-2.8.0/check-relaxng-test-suite2.py
  0:0  error   syntax error while parsing AST from file                     r2c.bandit     error
 37:17 error   .has_key() is deprecated, use 'in'                           r2c.flake8     W601 https://lintlyci.github.io/Flake8Rules/rules/W601.html
 68:44 error   TabError: inconsistent use of tabs and spaces in indentation r2c.flake8     E999
 74:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
 91:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
128:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
145:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
180:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
206:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
228:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
253:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html

vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.1/ext/nokogiri/tmp/x86_64-apple-darwin13.2.0/ports/libxml2/2.8.0/libxml2-2.8.0/check-xinclude-test-suite.py
  0:0  error   syntax error while parsing AST from file                     r2c.bandit     error
 35:24 error   TabError: inconsistent use of tabs and spaces in indentation r2c.flake8     E999
104:3  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
110:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html

vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.1/ext/nokogiri/tmp/x86_64-apple-darwin13.2.0/ports/libxml2/2.8.0/libxml2-2.8.0/check-xml-test-suite.py
  0:0  error   syntax error while parsing AST from file                     r2c.bandit     error
 34:42 error   TabError: inconsistent use of tabs and spaces in indentation r2c.flake8     E999
 62:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
 88:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
114:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
141:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
168:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
201:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
231:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
267:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html

vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.1/ext/nokogiri/tmp/x86_64-apple-darwin13.2.0/ports/libxml2/2.8.0/libxml2-2.8.0/check-xsddata-test-suite.py
  0:0  error   syntax error while parsing AST from file                     r2c.bandit     error
 47:17 error   .has_key() is deprecated, use 'in'                           r2c.flake8     W601 https://lintlyci.github.io/Flake8Rules/rules/W601.html
 67:44 error   TabError: inconsistent use of tabs and spaces in indentation r2c.flake8     E999
 73:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
 90:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
127:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
144:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
178:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
204:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
226:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
251:5  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html

vendor/bundle/ruby/2.0.0/gems/nokogiri-1.6.1/ext/nokogiri/tmp/x86_64-apple-darwin13.2.0/ports/libxml2/2.8.0/libxml2-2.8.0/doc/apibuild.py
  0:0  error   syntax error while parsing AST from file                     r2c.bandit     error
100:21 error   TabError: inconsistent use of tabs and spaces in indentation r2c.flake8     E999
122:21 error   backticks are deprecated, use 'repr()'                       r2c.flake8     W604 https://lintlyci.github.io/Flake8Rules/rules/W604.html
124:20 error   backticks are deprecated, use 'repr()'                       r2c.flake8     W604 https://lintlyci.github.io/Flake8Rules/rules/W604.html
126:20 error   backticks are deprecated, use 'repr()'                       r2c.flake8     W604 https://lintlyci.github.io/Flake8Rules/rules/W604.html
208:2  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
230:2  error   do not use bare 'except'                                     r2c.flake8     E722 https://lintlyci.github.io/Flake8Rules/rules/E722.html
264:15 error   over-indented (comment)                                      r2c.flake8     E117 https://lintlyci.github.io/Flake8Rules/rules/E117.html
265:15 error   over-indented (comment)                                      r2c.flake8     E117 https://lintlyci.github.io/Flake8Rules/rules/E117.html
266:15 error   over-indented (comment)                                      r2c.flake8     E117 https://lintlyci.github.io/Flake8Rules/rules/E117.html
267:15 error   over-indented (comment)                                      r2c.flake8     E117 https://lintlyci.github.io/Flake8Rules/rules/E117.html
268:7  error   over-indented                                                r2c.flake8     E117 https://lintlyci.github.io/Flake8Rules/rules/E117.html
268:21 error   .has_key() is deprecated, use 'in'                           r2c.flake8     W601 https://lintlyci.github.io/Flake8Rules/rules/W601.html
270:24 error   .has_key() is deprecated, use 'in'                           r2c.flake8     W601 https://lintlyci.github.io/Flake8Rules/rules/W601.html
277:15 error   over-indented (comment)                                      r2c.flake8     E117 https://lintlyci.github.io/Flake8Rules/rules/E117.html
278:15 error   over-indented (comment)                                      r2c.flake8     E117 https://lintlyci.github.io/Flake8Rules/rules/E117.html
279:15 error   over-indented (comment)                                      r2c.flake8     E117 https://lintlyci.github.io/Flake8Rules/rules/E117.html
:
```

**Additional context**
User installed using pip3 install bento-cli.

**Comment by nbrahms** [comment]
@pabloest Would it be possible to have the user run `node_modules/eslint/bin/eslint.js --no-eslintrc -c .eslintrc.yml --debug .` locally and send us the output? Or can we get access to the codebase?

**Comment by pabloest** [comment]
@nbrahms Yes, I asked for that output.

**Comment by pabloest** [comment]
@nbrahms here’s the output:
```bash
$ node_modules/eslint/bin/eslint.js --no-eslintrc -c .eslintrc.yml --debug . 
/Users/[redacted]/master/[redacted]/ui/node_modules/eslint/lib/cli-engine/cli-engine.js:257
        ...calculateStatsPerFile(messages)
        ^^^

SyntaxError: Unexpected token ...
    at NativeCompileCache._moduleCompile (/Users/[redacted]/master/[redacted]/ui/node_modules/v8-compile-cache/v8-compile-cache.js:242:18)
    at Module._compile (/Users/[redacted]/master/[redacted]/ui/node_modules/v8-compile-cache/v8-compile-cache.js:186:36)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (/Users/[redacted]/master/[redacted]/ui/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/[redacted]/master/[redacted]/ui/node_modules/eslint/lib/cli-engine/index.js:3:23)
    at Module._compile (/Users/[redacted]/master/[redacted]/ui/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
```

**Comment by pabloest** [comment]
More details from the user:
```bash
I don’t have eslint installed. 

Mac-Pro$ node --version
v8.1.4
Mac-Pro$ npm --version
5.0.3
Mac-Pro$ which eslint
Mac-Pro$ which node
/Users/[redacted]/.nvm/versions/node/v8.1.4/bin/node
Mac-Pro$ which npm
/Users/[redacted]/.nvm/versions/node/v8.1.4/bin/npm
Mac-Pro$ 
```

**Comment by ulziibay** [comment]
Ack. Thank you very much for providing. Was able to reproduce this and actively working on a release that addresses this.

**Comment by dlukeomalley** [comment]
Closing out per @ulziibay's fix. Thank you again for reporting.
