### ISSUE TITLE
`bento install-hook` throws exception and has unfriendly error message if hook exists

### ISSUE THREAD

**Issue by daghan** [returntocorp/bento#90]
Make sure you are running the latest version of Bento.

**Describe the bug**
When running `bento install-hook` I get a very verbose error  message

**Expected result**
 There is already a legacy hook. Please remove or back it up.

**Actual result**

```bash
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/bento/__main__.py", line 14, in main
    cli()
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/bento/cli.py", line 718, in install_hook
    "There is already a legacy hook. Not sure what to do so just exiting for now."
Exception: There is already a legacy hook. Not sure what to do so just exiting for now.
✘ There was an exception There is already a legacy hook. Not sure what to do so just exiting for now.
```

**Additional context**
bento/0.1.0.post1

**Comment by dlukeomalley** [comment]
This is fixed in `bento/0.1.0.post1`! Thank you for filing.

```bash
$ bento install-hook
✔ Added Bento to your git pre-commit hooks.
$bento install-hook
✔ Bento already installed as a pre-commit hook
```
