### ISSUE TITLE
Error: Failed to load plugin '@typescript-eslint'

### ISSUE THREAD

**Issue by pabloest** [returntocorp/bento#96]
**Describe the bug**
Running `bento check` on a newly initialized project (https://github.com/zeit/now) results in an error.

**Expected result**
No errors.

**Actual result**
```console
  r2c.flake8: |███████████████| 00:02, 🍱

✘ Error while running r2c.eslint: Command '['./node_modules/eslint/bin/eslint.js', '--no-eslintrc', '-c', '.eslintrc.yml', '-f', 'json', '--ignore-pattern', '**/node_modules', '--ext', 'js,jsx,ts,tsx', '.']' returned non-zero exit status 2.
Error: Failed to load plugin '@typescript-eslint' declared in '--config': Cannot find module 'typescript'
Require stack:
- /Users/pabloestrada/sites/now/node_modules/tsutils/typeguard/2.8/node.js
- /Users/pabloestrada/sites/now/node_modules/tsutils/typeguard/2.9/node.js
- /Users/pabloestrada/sites/now/node_modules/tsutils/typeguard/3.0/node.js
- /Users/pabloestrada/sites/now/node_modules/tsutils/typeguard/3.2/node.js
- /Users/pabloestrada/sites/now/node_modules/tsutils/typeguard/node.js
- /Users/pabloestrada/sites/now/node_modules/tsutils/typeguard/index.js
- /Users/pabloestrada/sites/now/node_modules/tsutils/index.js
- /Users/pabloestrada/sites/now/node_modules/@typescript-eslint/eslint-plugin/dist/util/types.js
- /Users/pabloestrada/sites/now/node_modules/@typescript-eslint/eslint-plugin/dist/util/index.js
- /Users/pabloestrada/sites/now/node_modules/@typescript-eslint/eslint-plugin/dist/rules/adjacent-overload-signatures.js
- /Users/pabloestrada/sites/now/node_modules/@typescript-eslint/eslint-plugin/dist/rules/index.js
- /Users/pabloestrada/sites/now/node_modules/@typescript-eslint/eslint-plugin/dist/index.js
- /Users/pabloestrada/sites/now/node_modules/eslint/lib/cli-engine/config-array-factory.js
- /Users/pabloestrada/sites/now/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js
- /Users/pabloestrada/sites/now/node_modules/eslint/lib/cli-engine/cli-engine.js
- /Users/pabloestrada/sites/now/node_modules/eslint/lib/cli-engine/index.js
- /Users/pabloestrada/sites/now/node_modules/eslint/lib/cli.js
- /Users/pabloestrada/sites/now/node_modules/eslint/bin/eslint.js
Referenced from: /Users/pabloestrada/sites/now/.eslintrc.yml
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:780:15)
    at Function.Module._load (internal/modules/cjs/loader.js:685:27)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (/Users/pabloestrada/sites/now/node_modules/v8-compile-cache/v8-compile-cache.js:161:20)
    at Object.<anonymous> (/Users/pabloestrada/sites/now/node_modules/tsutils/typeguard/2.8/node.js:3:12)
    at Module._compile (/Users/pabloestrada/sites/now/node_modules/v8-compile-cache/v8-compile-cache.js:194:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
```

**Additional context**
bento/0.1.1b2
macOS 10.14.16

**Comment by dlukeomalley** [comment]
@pabloest Thanks for filing this. With your permission, I'd like to investigate this first thing on Monday. Is that ok with you?

**Comment by pabloest** [comment]
Sounds good, thanks!

**Comment by nbrahms** [comment]
@pabloest Can you try with 0.1.1b3? We had a fast-follow release to fix this issue.

**Comment by pabloest** [comment]
@nbrahms Sure. I reset the project / repo and then ran `bento init` followed by `bento check`:

```bash
 @pabloestrada  bento init
Creating default configuration at .bento.yml
✔ Created .bento.yml. Please check this file in to source control.

Detected project with node-js and Python

✔ Creating virtual environment for r2c.bandit
✔ Python package bandit will be installed
Installing {'eslint': Version('6.1.0'), 'eslint-config-airbnb': Version('18.0.1'), 'eslint-plugin-import': Version('2.18.2'), 'eslint-plugin-jsx-a11y': Version('6.2.3'), 'eslint-plugin-react': Version('7.14.3'), 'eslint-plugin-react-hooks': Version('1.7.0')}...
yarn add v1.19.1
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
⚠ Could not execute "yarn add --dev eslint@^6.1.0 eslint-config-airbnb@^18.0.1 eslint-plugin-import@^2.18.2 eslint-plugin-jsx-a11y@^6.2.3 eslint-plugin-react@^7.14.3 eslint-plugin-react-hooks@^1.7.0":
None

 Mon 14 Oct - 19:40  ~/sites/now   origin ☊ canary 2☀ 
 @pabloestrada  bento check
Running Bento checks...
  r2c.bandit: |               | 00:00, 🍜
  r2c.eslint: |               | 00:00, 🍜
Installing {'eslint': Version('6.1.0'), '✔ Creating virtual environment for r2c.flake8lint-plugin-import': Version('2.18.2'), 'eslint-plugin-jsx-a11y': Version('6.2.3'), 'eslint-plugin-react': Version('7.yarn add v1.19.1
error Running this command will add the dependency to the workspace root rather than the workspace itself, which might not be what you want - if you really meant it, make it explicit by running this command again with the -W flag (or --ignore-workspace-root-check).
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
  r2c.bandit: |███████████████| 00:01, 🍱✔ Python package flake8 will be installed
✔ Python package flake8-json will be installed


  r2c.flake8: |███████████████| 00:07, 🍱

✘ Error while running r2c.eslint: Command '['yarn', 'add', '--dev', 'eslint@^6.1.0', 'eslint-config-airbnb@^18.0.1', 'eslint-plugin-import@^2.18.2', 'eslint-plugin-jsx-a11y@^6.2.3', 'eslint-plugin-react@^7.14.3', 'eslint-plugin-react-hooks@^1.7.0']' returned non-zero exit status 1.



packages/now-python/now_init.py
155:9  error   'urllib.parse.urlencode' imported but unused                       r2c.flake8     F401

packages/now-python/test/fixtures/01-cowsay/another/index.py
  2:1  error   'cowpy.cow' imported but unused                                    r2c.flake8     F401

packages/now-python/test/fixtures/09-url-params/custom.py
  1:1  error   'flask.__version__' imported but unused                            r2c.flake8     F401

packages/now-python/test/fixtures/09-url-params/index.py
  1:1  error   'flask.__version__' imported but unused                            r2c.flake8     F401

packages/now-python/test/fixtures/13-wsgi-url-params-encoding/custom.py
  1:1  error   'flask.__version__' imported but unused                            r2c.flake8     F401

packages/now-python/test/fixtures/13-wsgi-url-params-encoding/index.py
  1:1  error   'flask.__version__' imported but unused                            r2c.flake8     F401

packages/now-static-build/test/fixtures/40-pelican/publishconf.py
 11:1  error   'from pelicanconf import *' used; unable to detect undefined names r2c.flake8     F403
 11:1  error   'pelicanconf.*' imported but unused                                r2c.flake8     F401

packages/now-static-build/test/fixtures/40-pelican/tasks.py
  6:1  error   'datetime' imported but unused                                     r2c.flake8     F401
  9:1  error   'invoke.util.cd' imported but unused                               r2c.flake8     F401

⚠ 10 findings in 7.67 s

To suppress all findings run `bento archive`.
```

**Comment by nbrahms** [comment]
@pabloest I'm going to open a new issue for nested yarn projects, separately from this issue.

**Comment by nbrahms** [comment]
Actually, it looks like you already did (thank you!), in #104 .
